### ISSUE TITLE
How to use this with TLS?

### ISSUE THREAD

**Issue by planetahuevo** [FGRibreau/stripe-update-card#2]
Hi, 
I am trying to setup this docker to use TLS ports but I am not able to make Rocket configuration work. 

Any tips or links I can use?
I am beginner on docker. 

Thanks!

**Comment by FGRibreau** [comment]
You might want to setup a reverse-proxy that do TLS in front of it :)

**Comment by planetahuevo** [comment]
Thanks for the reply. I have decided not to use it because for credit cards, SSL is a must imho.
